apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-probes-exporter
  name: k8s-probes-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-probes-exporter
  template:
    metadata:
      labels:
        app: k8s-probes-exporter
    spec:
      serviceAccountName: k8s-probes-exporter
      containers:
        - image: dfdsdk/k8s-probes-exporter:latest
          name: exporter
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: metrics