apiVersion: v1
kind: Service
metadata:
  name: k8s-probes-exporter
  namespace: monitoring
  labels:
    scrape-service-metrics: "true"
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
  selector:
    app: k8s-probes-exporter