apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-probes-exporter-read
subjects:
  - kind: ServiceAccount
    name: k8s-probes-exporter
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: k8s-probes-exporter-read
  apiGroup: rbac.authorization.k8s.io