apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-probes-exporter
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - name: exporter
          image: dfdsdk/k8s-probes-exporter:prod
  selector:
    matchLabels:
      app: k8s-probes-exporter